### ISSUE TITLE
SSL or not?

### ISSUE THREAD

**Issue by Andromelus** [frbrkoala/node-red-contrib-fabric-blocks-listener#2]
Hi.
The documentation on node-red says no SSL supported (https://flows.nodered.org/node/node-red-contrib-fabric-blocks-listener).  However, you updated documentation here to remove this statement. So what is correct? Moreover, I am not able to use it with SSL. 

Can you make it clear please?

Thank you.

**Comment by frbrkoala** [comment]
Hi @floriancastelain . Yes I updated this doc after making some changes and testing it against IBM Blockchain Platform with TLS enabled. I believe NPM didn't pick up the update so it's properly propagated to the node-red catalogue. I'll give it another try. 

But to make it clear, TLS was tested successfully using the approach described in the doc: by sending config params from the standard Inject node. How you were testing it on your side?

**Comment by Andromelus** [comment]
Alright, thanks. i'll keep an eye on it.
I am testing it the exact same way, with IBM blockchain platform (V1, not V2).

Thank you

**Comment by Andromelus** [comment]
Another question I have is: What exactly is sslHostName? Because I cannot find anything about that anywhere. Is it peer name? Organization name? Organization ID?

**Comment by frbrkoala** [comment]
Hi @floriancastelain . `sslHostName` is a host name of the peer as used in the TLS certificate in case it's different from the actual host end point. It's just an exposure of `ssl-target-name-override` parameter of peer config in Fabric Node SDK: https://fabric-sdk-node.github.io/release-1.4/global.html#ConnectionOpts

BTW, check you don't have new line characters in the certs and private keys. If there are, please replace them with `\n` as in the example.

**Comment by Andromelus** [comment]
Hi. Sorry for late answer @frbrkoala . I am not using your node anymore, I am using node-red-contrib-fabric that I am modifying for my needs (https://github.com/floriancastelain/node-red-contrib-fabric). It had more code to base my work on. 
However I am actually thinking on integrating a full block listener (something like you did) but with "dynamic filtering". 

So maybe we can close this one? I am not testing anymore.
